import type { SceneAudioConfig } from '../../types';
import { AUDIO_HOOKS } from '../../audio/hooks';

export const ACT_FOUR_AUDIO = {
  tracks: {
    background: {
      id: 'act-4-e-dance',
      src: '/audio/act-4/music/e-dance.mp3',
      loop: true,
      volume: 0.62,
      resume: true,
    },
    artifacts: 'act-4-artifact-override',
    win: 'act-4-press-to-win',
    showdown: 'act-4-showdown',
    credits: 'act-4-credits',
    ending: 'act-4-ending',
    animeShowdown: {
      id: 'act-4-anime-showdown',
      src: '/audio/act-4/music/anime-showdown-loud.mp3',
      loop: true,
      volume: 1,
    },
    valeraFinale: {
      id: 'act-4-valera-finale-kikile',
      src: '/audio/act-4/music/kikile.mp3',
      loop: true,
      volume: 0.72,
      resume: true,
    },
  },
  cues: {
    approach: 'background',
    reveal: 'background',
    cards: 'background',
    artifacts: 'artifacts',
    win: 'win',
    showdown: 'showdown',
    credits: 'credits',
    ending: 'ending',
    animeShowdown: 'animeShowdown',
    valeraFinale: 'valeraFinale',
  },
  voice: {
    approach: 'act-4-voice-approach',
    footNotice: 'act-4-sfx-foot-notice',
    reveal: 'act-4-voice-reveal',
    revealZoomOut: 'act-4-sfx-reveal-zoom-out',
    revealZoomIn: 'act-4-sfx-reveal-zoom-in',
    cards: 'act-4-voice-cards',
    zeroCardPlayed: 'act-4-sfx-zero-card-played',
    supportCardReveal: 'act-4-sfx-support-card-reveal',
    supportCardPlayed: 'act-4-sfx-support-card-played',
    valeraSummon: 'act-4-sfx-valera-summon',
    valeraIdle: 'act-4-sfx-valera-idle',
    valeraTransform: 'act-4-sfx-valera-transform',
    valeraSecondTransform: 'act-4-sfx-valera-second-transform',
    valeraConjure: 'act-4-sfx-valera-conjure',
    valeraSupport: 'act-4-sfx-valera-support',
    valeraReverseSummon: 'act-4-sfx-valera-reverse-summon',
    artifacts: 'act-4-voice-artifacts',
    artifactConsume: 'act-4-sfx-artifact-consume',
    win: 'act-4-voice-win',
    pressToWin: 'act-4-sfx-press-to-win',
    showdownStart: {
      id: 'act-4-sfx-naruto-screaming',
      src: '/audio/act-4/sfx/naruto-screaming.mp3',
      volume: 0.95,
    },
    creditsStrike: 'act-4-sfx-credits-strike',
    ending: 'act-4-voice-ending',
  },
  sfx: {
    postShowdownAww: {
      id: 'act-4-sfx-post-showdown-aww',
      src: '/audio/act-4/sfx/studio-audience-awwww.mp3',
      volume: 0.92,
    },
  },
  hooks: {
    [AUDIO_HOOKS.actFour.approachStart]: { music: 'approach', voice: 'approach' },
    [AUDIO_HOOKS.actFour.footNotice]: { voice: 'footNotice' },
    [AUDIO_HOOKS.actFour.revealStart]: { music: 'reveal', voice: 'reveal' },
    [AUDIO_HOOKS.actFour.revealZoomOut]: { voice: 'revealZoomOut' },
    [AUDIO_HOOKS.actFour.revealZoomIn]: { voice: 'revealZoomIn' },
    [AUDIO_HOOKS.actFour.cardsStart]: { music: 'cards', voice: 'cards' },
    [AUDIO_HOOKS.actFour.zeroCardPlayed]: { voice: 'zeroCardPlayed' },
    [AUDIO_HOOKS.actFour.supportCardReveal]: { voice: 'supportCardReveal' },
    [AUDIO_HOOKS.actFour.supportCardPlayed]: { music: 'valeraFinale', voice: 'supportCardPlayed' },
    [AUDIO_HOOKS.actFour.valeraSummon]: { voice: 'valeraSummon' },
    [AUDIO_HOOKS.actFour.valeraIdle]: { voice: 'valeraIdle' },
    [AUDIO_HOOKS.actFour.valeraTransform]: { voice: 'valeraTransform' },
    [AUDIO_HOOKS.actFour.valeraSecondTransform]: { voice: 'valeraSecondTransform' },
    [AUDIO_HOOKS.actFour.valeraConjure]: { voice: 'valeraConjure' },
    [AUDIO_HOOKS.actFour.valeraSupport]: { voice: 'valeraSupport' },
    [AUDIO_HOOKS.actFour.valeraReverseSummon]: { voice: 'valeraReverseSummon' },
    [AUDIO_HOOKS.actFour.artifactsStart]: { voice: 'artifacts' },
    [AUDIO_HOOKS.actFour.artifactConsume]: { voice: 'artifactConsume' },
    [AUDIO_HOOKS.actFour.winReady]: { voice: 'win' },
    [AUDIO_HOOKS.actFour.pressToWin]: { stopVoice: true, music: 'valeraFinale', sfx: 'postShowdownAww' },
    [AUDIO_HOOKS.actFour.showdownStart]: { stopVoice: true, pauseMusic: true, voice: 'showdownStart', restartVoice: true },
    [AUDIO_HOOKS.actFour.showdownMusic]: { music: 'animeShowdown' },
    [AUDIO_HOOKS.actFour.creditsStart]: { stopVoice: true },
    [AUDIO_HOOKS.actFour.creditsStrike]: { voice: 'creditsStrike' },
    [AUDIO_HOOKS.actFour.endingStart]: { music: 'ending', voice: 'ending' },
  },
} as const satisfies SceneAudioConfig;
