export const AUDIO_HOOKS = {
  shared: {
    collection: 'shared:collection',
  },
  director: {
    briefing: 'director:briefing',
    victory: 'director:victory',
  },
  actOne: {
    introDialogue: 'act-1:intro-dialogue',
    exploreStart: 'act-1:explore:start',
    encounterStartOpening: 'act-1:encounter:opening:start',
    encounterStartSecond: 'act-1:encounter:second:start',
    encounterStartBoss: 'act-1:encounter:boss:start',
    battleStartOpening: 'act-1:battle:opening:start',
    battleStartSecond: 'act-1:battle:second:start',
    battleStartBoss: 'act-1:battle:boss:start',
    battleVictory: 'act-1:battle:victory',
    bossVictory: 'act-1:boss:victory',
    artifactDrop: 'act-1:artifact:drop',
    artifactOutro: 'act-1:artifact:outro',
  },
  actTwo: {
    introDialogue: 'act-2:intro-dialogue',
    exploreStart: 'act-2:explore:start',
    encounterStartOpening: 'act-2:encounter:opening:start',
    encounterStartDuo: 'act-2:encounter:duo:start',
    encounterStartBoss: 'act-2:encounter:boss:start',
    encounterTransition: 'act-2:encounter:transition',
    battleStartOpening: 'act-2:battle:opening:start',
    battleStartDuo: 'act-2:battle:duo:start',
    battleStartBoss: 'act-2:battle:boss:start',
    battleVictory: 'act-2:battle:victory',
    bossVictory: 'act-2:boss:victory',
    partnerJoin: 'act-2:partner:join',
    postSecondEncounter: 'act-2:encounter:second:post',
    postBoss: 'act-2:boss:post',
    artifactDrop: 'act-2:artifact:drop',
  },
  actThree: {
    intro: 'act-3:intro',
    checkpointOneStart: 'act-3:checkpoint-one:start',
    documentsStart: 'act-3:documents:start',
    checkpointTwoStart: 'act-3:checkpoint-two:start',
    shot: 'act-3:shot',
    hit: 'act-3:hit',
    shootoutStart: 'act-3:shootout:start',
    shootoutVictory: 'act-3:shootout:victory',
  },
  actFour: {
    approachStart: 'act-4:approach:start',
    footNotice: 'act-4:foot:notice',
    revealStart: 'act-4:reveal:start',
    revealZoomOut: 'act-4:reveal:zoom-out',
    revealZoomIn: 'act-4:reveal:zoom-in',
    cardsStart: 'act-4:cards:start',
    zeroCardPlayed: 'act-4:cards:zero-card-played',
    supportCardReveal: 'act-4:support-card:reveal',
    supportCardPlayed: 'act-4:support-card:played',
    valeraSummon: 'act-4:valera:summon',
    valeraIdle: 'act-4:valera:idle',
    valeraTransform: 'act-4:valera:transform',
    valeraSecondTransform: 'act-4:valera:second-transform',
    valeraConjure: 'act-4:valera:conjure',
    valeraSupport: 'act-4:valera:support',
    valeraReverseSummon: 'act-4:valera:reverse-summon',
    artifactsStart: 'act-4:artifacts:start',
    artifactConsume: 'act-4:artifact:consume',
    winReady: 'act-4:win:ready',
    pressToWin: 'act-4:win:press',
    showdownStart: 'act-4:showdown:start',
    showdownMusic: 'act-4:showdown:music',
    creditsStart: 'act-4:credits:start',
    creditsStrike: 'act-4:credits:strike',
    endingStart: 'act-4:ending:start',
  },
} as const;
