import type { SceneAudioConfig } from '../../types';
import { AUDIO_HOOKS } from '../../audio/hooks';

export const ACT_TWO_AUDIO = {
  tracks: {
    field: {
      id: 'act-2-blue-fields',
      src: '/audio/act-2/music/blue-fields.mp3',
      loop: true,
      volume: 0.62,
      resume: true,
    },
    encounterIntro: 'act-2-encounter-sting',
    battle: 'act-2-battle',
    bossBattle: 'act-2-boss',
    victory: 'act-2-victory',
    artifact: 'act-2-artifact',
    openingEncounter: {
      id: 'act-2-nyu-yorkskij-taksist',
      src: '/audio/act-2/music/nyu-yorkskij-taksist.mp3',
      loop: true,
      volume: 0.72,
      startTime: 34,
    },
    khinkaliEncounter: {
      id: 'act-2-khinkali-armyane-vsego-mira',
      src: '/audio/act-2/music/armyane-vsego-mira.mp3',
      loop: true,
      volume: 0.72,
    },
    secondEncounter: {
      id: 'act-2-govnari',
      src: '/audio/act-2/music/govnari.mp4',
      loop: true,
      volume: 0.72,
    },
  },
  cues: {
    introDialogue: 'field',
    explore: 'field',
    openingBattle: 'battle',
    duoBattle: 'battle',
    bossBattle: 'bossBattle',
    bossVictory: 'victory',
    artifactDrop: 'artifact',
    openingEncounter: 'openingEncounter',
    khinkaliEncounter: 'khinkaliEncounter',
    secondEncounter: 'secondEncounter',
  },
  voice: {
    introDialogue: 'act-2-voice-intro',
    openingEncounter: 'act-2-voice-opening-encounter',
    partnerJoin: 'act-2-voice-partner-join',
    duoEncounter: 'act-2-voice-duo-encounter',
    postSecondEncounter: 'act-2-voice-post-second',
    bossEncounter: 'act-2-voice-boss-encounter',
    postBoss: 'act-2-voice-post-boss',
    artifactDrop: 'act-2-voice-artifact-drop',
  },
  sfx: {
    collection: {
      id: 'shared-arcade-bonus',
      src: '/audio/shared/sfx/arcade-bonus.mp3',
      volume: 0.9,
    },
  },
  hooks: {
    [AUDIO_HOOKS.shared.collection]: { sfx: 'collection' },
    [AUDIO_HOOKS.actTwo.introDialogue]: { music: 'introDialogue', voice: 'introDialogue' },
    [AUDIO_HOOKS.actTwo.exploreStart]: { music: 'explore' },
    [AUDIO_HOOKS.actTwo.encounterStartOpening]: { music: 'openingEncounter', voice: 'openingEncounter' },
    [AUDIO_HOOKS.actTwo.encounterStartDuo]: { music: 'secondEncounter', voice: 'duoEncounter' },
    [AUDIO_HOOKS.actTwo.encounterStartBoss]: { music: 'khinkaliEncounter', voice: 'bossEncounter' },
    [AUDIO_HOOKS.actTwo.encounterTransition]: { music: 'encounterIntro' },
    [AUDIO_HOOKS.actTwo.battleStartOpening]: {},
    [AUDIO_HOOKS.actTwo.battleStartDuo]: {},
    [AUDIO_HOOKS.actTwo.battleStartBoss]: {},
    [AUDIO_HOOKS.actTwo.battleVictory]: { music: 'victory' },
    [AUDIO_HOOKS.actTwo.bossVictory]: {},
    [AUDIO_HOOKS.actTwo.partnerJoin]: { voice: 'partnerJoin' },
    [AUDIO_HOOKS.actTwo.postSecondEncounter]: { voice: 'postSecondEncounter' },
    [AUDIO_HOOKS.actTwo.postBoss]: { voice: 'postBoss' },
    [AUDIO_HOOKS.actTwo.artifactDrop]: { voice: 'artifactDrop' },
  },
} as const satisfies SceneAudioConfig;
