export const ACT_TWO_UI = {
  hudEyebrow: 'Акт 2',
  dialogueEyebrow: 'Диалог акта 2',
  fieldTitle: 'Квест по открытию офиса',
  fieldBody: 'Используйте WASD, стрелки или стик. После короткой прогулки сработает постановочное столкновение.',
  exploreResumedTitle: 'Продвижение по маршруту',
  battleIncomingTitle: 'Бой начинается',
  artifactDropTitle: 'Реликвия акта',
  artifactCollectedTitle: 'Реликвия получена',
  dialogueNext: 'Press X',
  startWalking: 'Press X',
  engage: 'Press X',
  continueExploration: 'Press X',
  walkOn: 'Press X',
  revealRelic: 'Press X',
  attack: 'Атака',
  ability: 'Навык',
  guard: 'Защита',
  back: 'Назад',
  attackTarget: 'Цель атаки',
  abilityTarget: 'Цель навыка',
  targetHelp: 'WASD или стик меняет цель. Enter или X подтверждает. Esc или O возвращает назад.',
  targetCaption: 'Выберите цель через WASD или стик, затем нажмите Enter, Space или X.',
  collectArtifact: 'Press X',
  partnerPlaceholder: 'Временный портрет союзника',
  enemyPlaceholder: 'Временный портрет противника',
  genericPlaceholder: 'Временный портрет',
  battlePhase: 'Фаза боя',
  turnSuffix: 'ход',
} as const;
